import type { MdGrant } from '../../src/adapter';

/** Deterministic fixture based on a live Maryland Community Compass record. */
export const ca1Fixture: MdGrant = {
  id: 1046,
  slug: 'build-our-future-grant-pilot-program',
  program_name: 'Build Our Future Grant Program',
  agency: 'Maryland Economic Development Corporation (MEDCO)',
  URL: 'https://www.medco-corp.com/programs/build-our-future-grant-program',
  program_description: 'Matching grants for Maryland innovation infrastructure projects.',
  is_accepting_applications: true,
  is_recurring: true,
  data_quality: 'high',
  funding_source: 'public',
  geographic_scope: 'statewide',
  assistance_type: ['grant'],
  assistance_description: 'Matching grants of up to $2 million per entity per fiscal year.',
  eligible_industries: ['Manufacturing', 'Information'],
  eligible_counties: ['All'],
  eligible_municipalities: [],
  eligible_regions: [],
  eligible_incentive_areas: ['RISE Zones'],
  eligible_organization_types: ['for-profit', 'non-profit', 'government'],
  business_stage: 'any',
  application_deadline_string: 'Rolling basis; program authorized through June 30, 2030',
  application_deadline_date: '2030-06-30',
  application_process_overview: 'Apply through the MEDCO online portal.',
  program_audience: 'Maryland businesses, nonprofits, local governments, and colleges.',
  use_of_funds: 'Innovation infrastructure hard costs.',
  geographic_eligibility: 'Available statewide in Maryland.',
  requirements_list: ['Applicant must be located in Maryland', 'Matching funds are required'],
  contact_name: 'Nick Henninger-Ayoub',
  contact_email: 'nhenninger@medco-corp.com',
  contact_phone: '',
  source_count: 2,
  source_urls: ['https://commerce.maryland.gov/fund/build-our-future-grant-program'],
  attachment_urls: ['https://commerce.maryland.gov/Documents/build-our-future-faq.pdf'],
  created_at: '2026-07-02T17:19:54.606265-04:00',
  updated_at: '2026-08-17T17:06:14.786290-04:00',
};

export const ca2FixtureEdgeCases: MdGrant = {
  ...ca1Fixture,
  id: 2048,
  slug: 'confirm-with-agency-program',
  program_name: 'Confirm With Agency Program',
  is_accepting_applications: false,
  is_recurring: false,
  application_deadline_string: '',
  application_deadline_date: '',
  assistance_description: 'Award amount varies.',
  eligible_organization_types: ['individuals'],
  contact_name: '',
  contact_email: '',
  source_urls: [],
  attachment_urls: [],
};
